# Enables strict dependency management and deterministic installs
enableImmutableInstalls: true

# Skips lifecycle scripts (like postinstall) when installing packages
enableScripts: false

# Ensures Yarn uses the exact versions specified in the lockfile
preferImmutableInstalls: true

# Allows ignoring peer dependency conflicts if needed
peerDependencyRules:
  ignoreMissing: true

# Configures Yarn to work with `yarn dlx` for npx-like functionality
packageExtensions:
  '@semantic-release/changelog@*':
    peerDependencies:
      '@semantic-release/core': '*'
  '@semantic-release/git@*':
    peerDependencies:
      '@semantic-release/core': '*'

# Ensures production installations omit devDependencies
enableGlobalCache: true
preferFrozenLockfile: true

# Sets up fallback behavior for Yarn commands
defaultSemverRangePrefix: '^'

# Prevents unnecessary dependency checks during development
nodeLinker: 'node-modules'

# Enables resolutions for overriding dependency versions when necessary
resolutions:
  'conflicting-package': 'desired-version'

# Enables globally shared cache
globalFolder: './.yarn/cache'

# Default settings for CI environments
ci:
  enableMessageNames: false
  immutable: true
  immutableCache: true
  checkCache: true
